language: erlang
otp_release:
  - 22.0
  - 21.3
  - 21.0
  - 20.3
before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
script:
  - ./rebar3 compile
  - ./rebar3 dialyzer
